name: "detector"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 512, 512 ]
  }
]
output [
  {
    name: "boxes"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "labels"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }  
]

# Specify GPU instance.
instance_group {
  kind: KIND_GPU
  count: 1
  gpus: 0
}